<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();?>
<?php $baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);?>
<?php if ($block->getBannerCollection() && $block->getBannerCollection()->getSize() > 0) : ?>
    <div class="vs7_promobanner-container">
    <?php foreach ($block->getBannerCollection() as $banner): ?>
        <div class="vs7_promobanner-banner">
            <a href="<?php echo $banner->getUrlKey(); ?>">
                <img src="<?php echo rtrim($baseUrl, '/').$banner->getImage(); ?>" alt="<?php echo $banner->getName(); ?>" title="<?php echo $banner->getName(); ?>"/>
            </a>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif;?>
